# Generated by Django 5.0.6 on 2024-06-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peptaloid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peptaloid',
            name='carbon_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
