#models.py
from django.db import models

# Create your models here.

class Peptaloid(models.Model):
    peptaloid_id = models.CharField(primary_key=True, max_length=50)
    coconut_id = models.CharField(max_length=50, blank=True, null=True)
    npatlas_id = models.CharField(max_length=50, blank=True, null=True)
    supernatural_id = models.CharField(max_length=50, blank=True, null=True)
    zinc_id = models.CharField(max_length=50, blank=True, null=True)
    InChIKey = models.CharField(max_length=255, blank=True, null=True)
    Compound_InChI = models.TextField(blank=True, null=True)
    smiles = models.CharField(max_length=1000, blank=True, null=True)
    MolecularFormula = models.CharField(max_length=255, blank=True, null=True)
    IUPAC_Name = models.CharField(max_length=2000, blank=True, null=True)
    Compound_Name = models.CharField(max_length=1000, blank=True, null=True)
    origin_type = models.CharField(max_length=255, blank=True, null=True)
    genus = models.CharField(max_length=255, blank=True, null=True)
    origin_species = models.CharField(max_length=255, blank=True, null=True)
    carbon_count = models.IntegerField(blank=True, null=True)
    SlogP = models.FloatField(blank=True, null=True)
    TPSA = models.FloatField(blank=True, null=True)
    Exact_MW = models.FloatField(blank=True, null=True)
    Num_Rotatable_Bonds = models.IntegerField(blank=True, null=True)
    Num_HBD = models.IntegerField(blank=True, null=True)
    Num_HBA = models.IntegerField(blank=True, null=True)
    Num_Amide_Bonds = models.IntegerField(blank=True, null=True)
    Num_Hetero_Atoms = models.IntegerField(blank=True, null=True)
    Num_Heavy_Atoms = models.IntegerField(blank=True, null=True)
    Num_Atoms = models.IntegerField(blank=True, null=True)
    Num_StereoCenters = models.IntegerField(blank=True, null=True)
    Num_Aromatic_Rings = models.IntegerField(blank=True, null=True)
    Num_Saturated_Rings = models.IntegerField(blank=True, null=True)
    Num_Aliphatic_Rings = models.IntegerField(blank=True, null=True)
    CX_LogP = models.FloatField(blank=True, null=True)
    CX_LogD = models.FloatField(blank=True, null=True)
    Heavy_Atoms = models.IntegerField(blank=True, null=True)
    Lipinski = models.IntegerField(blank=True, null=True)
    total_charge = models.IntegerField(blank=True, null=True)
    qed_score = models.FloatField(blank=True, null=True)
    Alcohol = models.IntegerField(blank=True, null=True)
    Aldehyde = models.IntegerField(blank=True, null=True)
    Ketone = models.IntegerField(blank=True, null=True)
    Carboxylic_Acid = models.IntegerField(blank=True, null=True)
    Amine = models.IntegerField(blank=True, null=True)
    Thiol = models.IntegerField(blank=True, null=True)
    AMES = models.FloatField(blank=True, null=True)
    BBB_Martins = models.FloatField(blank=True, null=True)
    Bioavailability_Ma = models.FloatField(blank=True, null=True)
    CYP1A2_Veith = models.FloatField(blank=True, null=True)
    CYP2C19_Veith = models.FloatField(blank=True, null=True)
    CYP2C9_Substrate_CarbonMangels = models.FloatField(blank=True, null=True)
    CYP2C9_Veith = models.FloatField(blank=True, null=True)
    CYP2D6_Substrate_CarbonMangels = models.FloatField(blank=True, null=True)
    CYP2D6_Veith = models.FloatField(blank=True, null=True)
    CYP3A4_Substrate_CarbonMangels = models.FloatField(blank=True, null=True)
    CYP3A4_Veith = models.FloatField(blank=True, null=True)
    Carcinogens_Lagunin = models.FloatField(blank=True, null=True)
    ClinTox = models.FloatField(blank=True, null=True)
    DILI = models.FloatField(blank=True, null=True)
    HIA_Hou = models.FloatField(blank=True, null=True)
    NR_AR_LBD = models.FloatField(blank=True, null=True)
    NR_AR = models.FloatField(blank=True, null=True)
    NR_AhR = models.FloatField(blank=True, null=True)
    NR_Aromatase = models.FloatField(blank=True, null=True)
    NR_ER_LBD = models.FloatField(blank=True, null=True)
    NR_ER = models.FloatField(blank=True, null=True)
    NR_PPAR_gamma = models.FloatField(blank=True, null=True)
    PAMPA_NCATS = models.FloatField(blank=True, null=True)
    Pgp_Broccatelli = models.FloatField(blank=True, null=True)
    SR_ARE = models.FloatField(blank=True, null=True)
    SR_ATAD5 = models.FloatField(blank=True, null=True)
    SR_HSE = models.FloatField(blank=True, null=True)
    SR_MMP = models.FloatField(blank=True, null=True)
    SR_p53 = models.FloatField(blank=True, null=True)
    Skin_Reaction = models.FloatField(blank=True, null=True)
    hERG = models.FloatField(blank=True, null=True)
    Caco2_Wang = models.FloatField(blank=True, null=True)
    Clearance_Hepatocyte_AZ = models.FloatField(blank=True, null=True)
    Clearance_Microsome_AZ = models.FloatField(blank=True, null=True)
    Half_Life_Obach = models.FloatField(blank=True, null=True)
    HydrationFreeEnergy_FreeSolv = models.FloatField(blank=True, null=True)
    LD50_Zhu = models.FloatField(blank=True, null=True)
    Lipophilicity_AstraZeneca = models.FloatField(blank=True, null=True)
    PPBR_AZ = models.FloatField(blank=True, null=True)
    Solubility_AqSolDB = models.FloatField(blank=True, null=True)
    VDss_Lombardo = models.FloatField(blank=True, null=True)
    Lipinski_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    AMES_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    BBB_Martins_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    Bioavailability_Ma_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    CYP1A2_Veith_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    CYP2C19_Veith_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    CYP2C9_Substrate_CarbonMangels_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    CYP2C9_Veith_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    CYP2D6_Substrate_CarbonMangels_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    CYP2D6_Veith_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    CYP3A4_Substrate_CarbonMangels_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    CYP3A4_Veith_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    Carcinogens_Lagunin_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    ClinTox_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    DILI_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    HIA_Hou_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    NR_AR_LBD_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    NR_AR_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    NR_AhR_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    NR_Aromatase_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    NR_ER_LBD_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    NR_ER_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    NR_PPAR_gamma_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    PAMPA_NCATS_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    Pgp_Broccatelli_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    SR_ARE_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    SR_ATAD5_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    SR_HSE_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    SR_MMP_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    SR_p53_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    Skin_Reaction_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    hERG_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    Caco2_Wang_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    Clearance_Hepatocyte_AZ_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    Clearance_Microsome_AZ_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    Half_Life_Obach_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    HydrationFreeEnergy_FreeSolv_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    LD50_Zhu_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    Lipophilicity_AstraZeneca_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    PPBR_AZ_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    Solubility_AqSolDB_drugbank_approved_percentile = models.FloatField(blank=True, null=True)
    VDss_Lombardo_drugbank_approved_percentile = models.FloatField(blank=True, null=True)

#    class Meta:
#        managed = False
#        db_table = 'peptaloid2'
